//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_MotionSickness : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.motionSickness_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Boolean Shoot
        {
            get
            {
                return SteamVR_Actions.motionSickness_Shoot;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.motionSickness_SnapTurnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.motionSickness_SnapTurnRight;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonHandLeft
        {
            get
            {
                return SteamVR_Actions.motionSickness_SkeletonHandLeft;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonHandRight
        {
            get
            {
                return SteamVR_Actions.motionSickness_SkeletonHandRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.motionSickness_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.motionSickness_Pose;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Move
        {
            get
            {
                return SteamVR_Actions.motionSickness_Move;
            }
        }
        
        public virtual SteamVR_Action_Boolean TeleportBack
        {
            get
            {
                return SteamVR_Actions.motionSickness_TeleportBack;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.motionSickness_Haptic;
            }
        }
    }
}
